### ISSUE TITLE
Add container registry rule

### ISSUE THREAD

**Issue by frjcomp** [mazen160/secrets-patterns-db#21]
Hey I very much like this project and I'm using it in one of my own.

I found one rule to be missing and I'm unsure where to place it.

```yaml
  - pattern:
      name: docker_registry_auth
      regex: auth":.*"(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{4}|[A-Za-z0-9+\/]{3}=|[A-Za-z0-9+\/]{2}={2})
      confidence: high
```

Could you add it or tell me where I need to insert it?

cheers
