### ISSUE TITLE
Inconsistent Indentation in YAML Files

### ISSUE THREAD

**Issue by dwisiswant0** [mazen160/secrets-patterns-db#5]
There are two YAML files with the same content but with different levels of indentation for the key-value pairs. This causes confusion and can make the YAML files harder to read and maintain.

From `db/`:
```yaml
patterns:
  - pattern:
      key: value
```

From `datasets/`:
```yaml
patterns:
  - pattern:
    key: value
```

The different indentation levels affect the structure of the data, and it is a best practice to maintain consistent indentation throughout a YAML file for readability and maintainability.
